[tool.poetry]
name = "unreasonable-llama-discord"
version = "0.1.0"
description = "Simple Discord bot using unreasonable-llama"
authors = ["SteelPh0enix <wojciech_olech@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
discord-py = "^2.4.0"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
