[messages]
edit-cooldown-ms = 750
length-limit = 1990
remove-reaction = "💀"

[commands]
prefix = "$"
inference-cmd = "llm"
help-cmd = "llm-help"
reset-conversation-cmd = "llm-reset"
stats-cmd = "llm-stats"

[bot]
default-system-prompt = "You are a helpful AI assistant. Assist the user best to your ability."
chat-database-path = "./chats.uldb"

[llama]
# URL is optional, if not provided it will be loaded from LLAMA_CPP_SERVER_URL env variable,
# as it's UnreasonableLlama fallback behaviour.
# url = "http://127.0.0.1:8080/"
server_timeout = 10000
